### ISSUE TITLE
SplitExample crashes in 3 column view on Ubuntu 22.04

### ISSUE THREAD

**Issue by lhoward** [stackotter/swift-cross-ui#49] opened 2023-06-24 01:21 UTC
```
#0  g_str_hash (v=0x0) at ../../../glib/ghash.c:2360
#1  0x00007ffff62b9519 in g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0x0, hash_table=0x7fffc001ff00) at ../../../glib/ghash.c:472
#2  g_hash_table_contains (hash_table=0x7fffc001ff00, key=0x0) at ../../../glib/ghash.c:1739
#3  0x00007ffff7b57cdd in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#4  0x00007ffff7a9f38f in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#5  0x00007ffff7a9b2e5 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#6  0x00007ffff7a9f286 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#7  0x00007ffff7a9b2e5 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#8  0x00007ffff7a9f286 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#9  0x00007ffff7a9b2e5 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#10 0x00007ffff7a9f286 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#11 0x00007ffff7a9b2e5 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#12 0x00007ffff7a9f286 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#13 0x00007ffff7a9b2e5 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#14 0x00007ffff7a9f286 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#15 0x00007ffff7aa4a2b in gtk_widget_unparent () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#16 0x000055555561e721 in $s3Gtk11ModifierBoxC8setChildyyAA6WidgetCSgF (newChild=..., self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/Gtk/Widgets/ModifierBox.swift:37
#17 0x0000555555664b27 in $s12SwiftCrossUI10EitherViewV6update_8childreny3Gtk11ModifierBoxC_AA0dE8ChildrenVyxq_GtF (widget=..., children=..., self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/Views/EitherView.swift:90
#18 0x0000555555664c3c in $s12SwiftCrossUI10EitherViewVyxq_GAA0E0A2aEP6update_8childreny6WidgetQz_7Content_8ChildrenQZtFTW () at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/Views/EitherView.swift:92
#19 0x0000555555652937 in $s12SwiftCrossUI13ViewGraphNodeC6update4withy7ContentQzSg_tF (content=..., self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/ViewGraph/ViewGraphNode.swift:35
#20 0x00005555556525a9 in $s12SwiftCrossUI13ViewGraphNodeC6update4withyx_tF (newView=..., self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/ViewGraph/ViewGraphNode.swift:30
#21 0x0000555555653035 in $s12SwiftCrossUI22ViewGraphNodeChildren1V6update4withyAA0D8Content1VyxG_tF (content=..., self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/ViewGraph/ViewGraphNodeChildren.swift:35
#22 0x00005555556530d8 in $s12SwiftCrossUI22ViewGraphNodeChildren1VyxGAA0deF8ChildrenA2aEP6update4withy7ContentQz_tFTW () at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/ViewGraph/ViewGraphNodeChildren.swift:36
#23 0x000055555565289e in $s12SwiftCrossUI13ViewGraphNodeC6update4withy7ContentQzSg_tF (content=..., self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/ViewGraph/ViewGraphNode.swift:34
#24 0x00005555556525a9 in $s12SwiftCrossUI13ViewGraphNodeC6update4withyx_tF (newView=..., self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/ViewGraph/ViewGraphNode.swift:30
#25 0x0000555555650f2b in $s12SwiftCrossUI9ViewGraphC6updateyyF (self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/ViewGraph/ViewGraph.swift:20
#26 0x0000555555650cf2 in $s12SwiftCrossUI9ViewGraphC3forACyxGx_tcfcyycfU_ () at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/ViewGraph/ViewGraph.swift:15
#27 0x00005555555936cc in $sIeg_ytIegr_TR () at /home/lukeh/CVSRoot/swift-cross-ui/Sources/Gtk/Callbacks/SignalBox.swift:17
#28 0x000055555559375c in $sytIegr_Ieg_TR () at /home/lukeh/CVSRoot/swift-cross-ui/Sources/Gtk/Callbacks/SignalBox.swift:17
#29 0x000055555564c51d in $s12SwiftCrossUI9PublisherC4sendyyFs5Int32VSvSgcfU_ () at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/State/Publisher.swift:22
#30 0x000055555564c5c9 in $s12SwiftCrossUI9PublisherC4sendyyFs5Int32VSvSgcfU_To () at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/State/Publisher.swift:16
#31 0x00007ffff62d5c44 in g_main_dispatch (context=0x5555559022a0) at ../../../glib/gmain.c:3419
#32 g_main_context_dispatch (context=0x5555559022a0) at ../../../glib/gmain.c:4137
#33 0x00007ffff632b258 in g_main_context_iterate.constprop.0 (context=context@entry=0x5555559022a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimised out>) at ../../../glib/gmain.c:4213
#34 0x00007ffff62d33e3 in g_main_context_iteration (context=context@entry=0x5555559022a0, may_block=may_block@entry=1) at ../../../glib/gmain.c:4278
#35 0x00007ffff5f21fb5 in g_application_run (application=0x5555558ff0e0, argc=<optimised out>, argv=<optimised out>) at ../../../gio/gapplication.c:2569
#36 0x00005555555914b7 in $s3Gtk11ApplicationC3runySiyAA0B6WindowCcF (windowCallback=..., self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/Gtk/Application.swift:41
#37 0x0000555555693899 in $s12SwiftCrossUI4_AppC3runyyF (self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/_App.swift:12
#38 0x0000555555644e24 in $s12SwiftCrossUI3AppPAAE4mainyyFZ (self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Sources/SwiftCrossUI/App.swift:26
#39 0x000055555564147e in $s12SplitExample0A3AppV5$mainyyFZ (self=...) at /home/lukeh/CVSRoot/swift-cross-ui/Examples/Split/SplitApp.swift:124
#40 0x0000555555641919 in SplitExample_main () at /home/lukeh/CVSRoot/swift-cross-ui/Examples/Split/SplitApp.swift:31
(gdb) 

```

**Comment by stackotter** [comment] 2023-06-24 07:36
Weird, is this reproducible for you? I just tried out the SplitExample on a 22.04.1 machine and didn't run into any issues. I played around with the example quite a bit too and didn't get any crashes

**Comment by lhoward** [comment] 2023-06-26 03:14
Seeing a similar crash in NavigationExample when popping back up to top level.

```
* thread #1, name = 'NavigationExamp', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x00007ffff62b8434 libglib-2.0.so.0`g_str_hash + 4
    frame #1: 0x00007ffff62b9519 libglib-2.0.so.0`g_hash_table_contains + 41
    frame #2: 0x00007ffff7b57cdd libgtk-4.so.1`___lldb_unnamed_symbol17255 + 1453
    frame #3: 0x00007ffff7a9f38f libgtk-4.so.1`___lldb_unnamed_symbol14851 + 351
    frame #4: 0x00007ffff7a9b2e5 libgtk-4.so.1`___lldb_unnamed_symbol14825 + 197
    frame #5: 0x00007ffff7a9f286 libgtk-4.so.1`___lldb_unnamed_symbol14851 + 86
    frame #6: 0x00007ffff7a9b2e5 libgtk-4.so.1`___lldb_unnamed_symbol14825 + 197
    frame #7: 0x00007ffff7a9f286 libgtk-4.so.1`___lldb_unnamed_symbol14851 + 86
    frame #8: 0x00007ffff7a9b2e5 libgtk-4.so.1`___lldb_unnamed_symbol14825 + 197
    frame #9: 0x00007ffff7a9f286 libgtk-4.so.1`___lldb_unnamed_symbol14851 + 86
    frame #10: 0x00007ffff7a9b2e5 libgtk-4.so.1`___lldb_unnamed_symbol14825 + 197
    frame #11: 0x00007ffff7a9f286 libgtk-4.so.1`___lldb_unnamed_symbol14851 + 86
    frame #12: 0x00007ffff7aa4a2b libgtk-4.so.1`gtk_widget_unparent + 331
    frame #13: 0x00007ffff7a060f8 libgtk-4.so.1`___lldb_unnamed_symbol13641 + 136
  * frame #14: 0x00007ffff7a08c82 libgtk-4.so.1`gtk_stack_remove + 242
    frame #15: 0x00005555556293bf NavigationExample`$s3Gtk5StackC6removeyyAA6WidgetCF at Stack.swift:37:13
    frame #16: 0x000055555567746d NavigationExample`$s12SwiftCrossUI23NavigationStackChildrenV6update4withyAA0dE7ContentVyxG_tF at NavigationStack.swift:179:31
    frame #17: 0x000055555567850c NavigationExample`$s12SwiftCrossUI23NavigationStackChildrenVyxGAA013ViewGraphNodeF0A2aEP6update4withy7ContentQz_tFTW at <compiler-generated>:0
    frame #18: 0x00005555556539ce NavigationExample`$s12SwiftCrossUI13ViewGraphNodeC6update4withy7ContentQzSg_tF at ViewGraphNode.swift:34:18
    frame #19: 0x00005555556536d9 NavigationExample`$s12SwiftCrossUI13ViewGraphNodeC6update4withyx_tF at ViewGraphNode.swift:30:9
    frame #20: 0x0000555555654165 NavigationExample`$s12SwiftCrossUI22ViewGraphNodeChildren1V6update4withyAA0D8Content1VyxG_tF at ViewGraphNodeChildren.swift:35:16
    frame #21: 0x0000555555654208 NavigationExample`$s12SwiftCrossUI22ViewGraphNodeChildren1VyxGAA0deF8ChildrenA2aEP6update4withy7ContentQz_tFTW at <compiler-generated>:0
    frame #22: 0x00005555556539ce NavigationExample`$s12SwiftCrossUI13ViewGraphNodeC6update4withy7ContentQzSg_tF at ViewGraphNode.swift:34:18
    frame #23: 0x00005555556536d9 NavigationExample`$s12SwiftCrossUI13ViewGraphNodeC6update4withyx_tF at ViewGraphNode.swift:30:9
    frame #24: 0x00005555556547c6 NavigationExample`$s12SwiftCrossUI22ViewGraphNodeChildren2V6update4withyAA0D8Content2Vyxq_G_tF at ViewGraphNodeChildren.swift:59:16
    frame #25: 0x000055555565488e NavigationExample`$s12SwiftCrossUI22ViewGraphNodeChildren2Vyxq_GAA0deF8ChildrenA2aEP6update4withy7ContentQz_tFTW at <compiler-generated>:0
    frame #26: 0x00005555556539ce NavigationExample`$s12SwiftCrossUI13ViewGraphNodeC6update4withy7ContentQzSg_tF at ViewGraphNode.swift:34:18
    frame #27: 0x00005555556536d9 NavigationExample`$s12SwiftCrossUI13ViewGraphNodeC6update4withyx_tF at ViewGraphNode.swift:30:9
    frame #28: 0x000055555565205b NavigationExample`$s12SwiftCrossUI9ViewGraphC6updateyyF at ViewGraph.swift:20:18
    frame #29: 0x0000555555651e22 NavigationExample`$s12SwiftCrossUI9ViewGraphC3forACyxGx_tcfcyycfU_ at ViewGraph.swift:15:18
    frame #30: 0x00005555555940cc NavigationExample`$sIeg_ytIegr_TR at <compiler-generated>:0
    frame #31: 0x000055555559415c NavigationExample`$sytIegr_Ieg_TR at <compiler-generated>:0
    frame #32: 0x000055555564d64d NavigationExample`$s12SwiftCrossUI9PublisherC4sendyyFs5Int32VSvSgcfU_ at Publisher.swift:22:21
    frame #33: 0x000055555564d6f9 NavigationExample`$s12SwiftCrossUI9PublisherC4sendyyFs5Int32VSvSgcfU_To at <compiler-generated>:0
    frame #34: 0x00007ffff62d5c44 libglib-2.0.so.0`g_main_context_dispatch + 372
    frame #35: 0x00007ffff632b258 libglib-2.0.so.0`___lldb_unnamed_symbol2709 + 488
    frame #36: 0x00007ffff62d33e3 libglib-2.0.so.0`g_main_context_iteration + 51
    frame #37: 0x00007ffff5f21fb5 libgio-2.0.so.0`g_application_run + 421
    frame #38: 0x0000555555591eb7 NavigationExample`$s3Gtk11ApplicationC3runySiyAA0B6WindowCcF at Application.swift:41:22
    frame #39: 0x00005555556949c9 NavigationExample`$s12SwiftCrossUI4_AppC3runyyF at _App.swift:12:16
    frame #40: 0x0000555555645f54 NavigationExample`$s12SwiftCrossUI3AppPAAE4mainyyFZ at App.swift:26:13
    frame #41: 0x000055555564296e NavigationExample`$s17NavigationExample0A3AppV5$mainyyFZ at <compiler-generated>:0
    frame #42: 0x0000555555642e09 NavigationExample`NavigationExample_main at NavigationApp.swift:29:8
    frame #43: 0x00007ffff5c42d90 libc.so.6`__libc_start_call_main(main=(NavigationExample`NavigationExample_main), argc=1, argv=0x00007fffffffe4d8) at libc_start_call_main.h:58:16
    frame #44: 0x00007ffff5c42e40 libc.so.6`__libc_start_main_impl(main=(NavigationExample`NavigationExample_main), argc=1, argv=0x00007fffffffe4d8, init=0x00007ffff7ffd040, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffe4c8) at libc-start.c:392:3
    frame #45: 0x00005555555913e5 NavigationExample`_start + 37
(lldb) 

```

**Comment by lhoward** [comment] 2023-06-26 03:19
Weird, can't seem to duplicate it now.

**Comment by stackotter** [comment] 2023-06-26 08:01
Thanks for the extra crash backtrace, seems like it’s some sort of issue with freeing before a view is actually not in use anymore. I’ll take a look at code in that area when I get back, hopefully it can be fixed with better memory management

**Comment by stackotter** [comment] 2023-11-07 04:58
I'll close this issue for now because quite a lot has changed internally since you encountered this crash, and some of the changes may have fixed the issue (which I can't confirm cause I can't reproduce it). If it ever happens again feel free to reopen this issue.

**Closed by stackotter** 2023-11-07 04:58 UTC
